language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly
matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
        - php: nightly
install:
    - composer install --prefer-dist
script:
    - ./bin/phpunit -c app
