language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly
install:
    - composer install --prefer-dist
script:
    - ./bin/phpunit --configuration app --coverage-clover build/logs/clover.xml
